export default [
    { text: "Divorce", weight: 10000 },
    { text: "Lawyer", weight: 9500 },
    { text: "Separation", weight: 9000 },
    { text: "Custody", weight: 8500 },
    { text: "Alimony", weight: 8000 },
    { text: "Marital Assets", weight: 7500 },
    { text: "Mediation", weight: 7000 },
    { text: "Child Support", weight: 6500 },
    { text: "Legal Advice", weight: 6000 },
    { text: "Spousal Support", weight: 5500 },
    { text: "Prenuptial", weight: 5200 },
    { text: "Postnuptial", weight: 5000 },
    { text: "Annulment", weight: 4800 },
    { text: "Property Division", weight: 4600 },
    { text: "Visitation Rights", weight: 4400 },
    { text: "Family Law", weight: 4200 },
    { text: "Marriage Counsel", weight: 4000 },
    { text: "Legal Separation", weight: 3900 },
    { text: "Case Law", weight: 3800 },
    { text: "Settlement", weight: 3700 },
    { text: "Contested Divorce", weight: 3600 },
    { text: "Uncontested Divorce", weight: 3500 },
    { text: "Joint Custody", weight: 3400 },
    { text: "Sole Custody", weight: 3300 },
    { text: "Parenting Plan", weight: 3200 },
    { text: "Matrimonial Law", weight: 3100 },
    { text: "Child Welfare", weight: 3000 },
    { text: "Paternity", weight: 2900 },
    { text: "Domestic Violence", weight: 2800 },
    { text: "Restraining Order", weight: 2700 },
    { text: "Legal Representation", weight: 2600 },
    { text: "Petition", weight: 2500 },
    { text: "Respondent", weight: 2400 },
    { text: "Petitioner", weight: 2300 },
    { text: "Decree", weight: 2200 },
    { text: "Affidavit", weight: 2100 },
    { text: "Adultery", weight: 2000 },
    { text: "Grounds for Divorce", weight: 1900 },
    { text: "Legal Fees", weight: 1800 },
    { text: "Consultation", weight: 1700 },
    { text: "Cohabitation", weight: 1600 },
    { text: "Appeal", weight: 1500 },
    { text: "Family Court", weight: 1400 },
    { text: "Child's Best Interest", weight: 1300 },
    { text: "Maintenance", weight: 1200 },
    { text: "Legal Proceedings", weight: 1100 },
    { text: "Guardianship", weight: 1000 },
    { text: "Equitable Distribution", weight: 900 },
    { text: "Resolution", weight: 800 },
    { text: "Arbitration", weight: 700 }
]
